# Generated by Django 3.2.4 on 2021-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_code',
            field=models.CharField(default=144022, max_length=10),
            preserve_default=False,
        ),
    ]
