# Generated by Django 3.2.4 on 2021-06-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='subject',
        ),
    ]
