# Generated by Django 3.2.4 on 2021-06-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210617_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='user_image',
            new_name='userprofile',
        ),
    ]
